env/dragonfly-amd64: add scripts for building GCE VM image
Now that Dragonfly runs on GCE, we can do that and retire the
one very slow reverse builder we are using today.

For golang/go#23060.

Change-Id: I2bd8c8be6735212ba6a8023327864b79dea08cf3
Reviewed-on: https://go-review.googlesource.com/c/build/+/419081
Auto-Submit: Russ Cox <rsc@golang.org>
Run-TryBot: Russ Cox <rsc@golang.org>
TryBot-Result: Gopher Robot <gobot@golang.org>
Reviewed-by: Heschi Kreinick <heschi@google.com>

diff --git a/env/dragonfly-amd64/buildlet b/env/dragonfly-amd64/buildlet
--- a/env/dragonfly-amd64/buildlet
+++ b/env/dragonfly-amd64/buildlet
@@ -19,6 +19,32 @@ stop_cmd=":"
 load_rc_config $name
 : ${buildlet_enable:="NO"}
 
+buildlet_resetnet()
+{
+	warn "buildlet resetting network"
+	ifconfig vtnet0 down
+	sleep 1
+	ifconfig vtnet0 up
+	sleep 1
+	dhclient vtnet0
+	sleep 1
+}
+
+buildlet_fixnet()
+{
+	# Some fraction of the time, the VM comes up unable to deliver UDP packets.
+	# If we detect this situation, by host -W 3 failing to look up metadata.google.internal,
+	# then reset the network interface (ifup/ifdown/dhclient).
+	# Once is almost always enough, so 10 attempts should drive the failure rate to zero.
+	for i in 0 1 2 3 4 5 6 7 8 9; do
+		if /usr/local/bin/host -W 3 metadata.google.internal; then
+			return 0
+		fi
+		buildlet_resetnet
+	done
+	return 1
+}
+
 buildlet_prestart()
 {
 	local buildlet_url
@@ -26,8 +52,20 @@ buildlet_prestart()
 	info $(netstat -rn)
 	info $(cat /etc/resolv.conf)
 
+	if ! buildlet_fixnet; then
+		warn "cannot fix network"
+		poweroff
+		return 1
+	fi
+
 	buildlet_url=$(/usr/local/bin/curl -s -H "Metadata-Flavor: Google" \
 		http://metadata.google.internal/computeMetadata/v1/instance/attributes/buildlet-binary-url)
+
+	if [ "$buildlet_url" = "" ]; then
+		warn "cannot find buildlet url"
+		poweroff
+		return 1
+	fi
 
 	if ! /usr/local/bin/curl -o /buildlet "${buildlet_url}"; then
 		warn "failed to download buildlet from ${buildlet_url}"
